CREATE TABLE users(
    id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE ,
    password VARCHAR(255) NOT NULL ,
    role VARCHAR(255) NOT NULL
);

CREATE TABLE orders(
    id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY ,
    total_price DECIMAL(13, 2) NOT NULL ,
    status VARCHAR(255) NOT NULL ,
    created_at TIMESTAMP NOT NULL ,
    user_id BIGINT REFERENCES users(id)
);

CREATE TABLE products(
    id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL ,
    description VARCHAR(255) NOT NULL ,
    price DECIMAL(13, 2) NOT NULL ,
    inventory INT NOT NULL
);

CREATE TABLE order_items(
    id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY ,
    quantity INT NOT NULL ,
    price DECIMAL(13, 2) NOT NULL ,
    product_id BIGINT NOT NULL REFERENCES products(id),
    order_id BIGINT NOT NULL REFERENCES orders(id)
);

CREATE TABLE cart_items(
    id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY ,
    quantity INT NOT NULL ,
    user_id BIGINT NOT NULL REFERENCES users(id),
    product_id BIGINT NOT NULL REFERENCES products(id)
)